# Changelog
Este archivo contiene los cambios realizados a los datos

2024-07-02
## Cambia
    - Ordena los datos por campo "started_at"
    - Remueve registros sin campo "member_casual"

2024-11-17
## Cambia
    - Remueve registros en blanco
    - Remueve registros con campos "start_station_name" y "start_station_id" en blanco
    - Remueve registros con campos "end_station_name" y "end_station_id" en blanco

2024-11-19
## Nuevo
    - Agrega columna "ride_length" la cual muestra el tiempo del viaje
    - Agrega columna "day_of_week" la cual muestra el dia de la semana

2024-12-01
## Cambia
    - Modifica el formato de la columna "ride_length" para mostrar solo 
      los minutos transcurridos en formato de texto

2024-12-02
## Carga
    - Carga los archivos a BigQuery como tablas independientes en el dataset 
      "capstone_project_data"

## Nuevo
    - Consolida los datos de todos los archivos en una tabla de BigQuery llamada 
      "consolidado_junio2023_mayo2024_raw" mediante SQL (sin remover duplicados)

2024-12-24
## Cambia
    - Remueve registros donde "ended_at" es menor que "started_at"

2025-01-02
## Cambia
    - Cambia el formato de "ride_length" de minutos a segundos

2025-01-03
## Carga
    - Carga los archivos a BigQuery con correcciones

2025-01-04
## Cambia
    - Remueve espacios en blanco de columnas string en BigQuery
    - Transforma columnas string a solo minúsculas en BigQuery

2025-01-05
## Cambia
    - Remueve los registros con "ride_length" igual a cero

## Carga
    - Carga los archivos a BigQuery con correcciones

## Cambia
    - Remueve espacios en blanco de columnas string en BigQuery
    - Transforma columnas string a solo minúsculas en BigQuery

2025-02-01
## Cambia
    - Modifica parámetro de función de day_of_week por started_at

2025-02-02
## Carga
    - Carga los archivos a BigQuery con correcciones